Repository expertiza/expertiza, pull requests merged in 2022-01, with the labels that each got.

#2139 Assignment helper refactor
  .travis.yml
  app/helpers/assignment_helper.rb
  app/helpers/report_formatter_helper.rb
  app/models/assignment_team.rb
  app/models/participant.rb
  app/models/response_map.rb
  config/application.rb
  lib/scoring.rb
  spec/controllers/grades_controller_spec.rb
  spec/controllers/reports_controller_spec.rb
  spec/helpers/assignment_helper_spec.rb
  spec/lib/scoring_spec.rb
  spec/models/assignment_team_spec.rb
  spec/models/participant_spec.rb
  spec/models/review_response_map_spec.rb
Labels: refactor

#2190 Remove broken report views
  app/helpers/report_formatter_helper.rb
  app/views/reports/_searchbox.html.erb
  app/views/reports/_summary_report.html.haml
  app/views/reports/_summary_reviewee_report.html.haml
  app/views/reports/response_report.html.haml
  spec/controllers/reports_controller_spec.rb
Labels: beta

#2031 Add admin_controller_spec.rb
  spec/controllers/admin_controller_spec.rb
Labels: testing

#2199 Course directory mandatory
  app/models/course.rb
  app/views/courses/_course.html.erb
  spec/models/course_spec.rb
Labels: beta

#2157 E2167 - Testing Team Related Files
  app/controllers/advertise_for_partner_controller.rb
  app/controllers/join_team_requests_controller.rb
  app/controllers/student_teams_controller.rb
  app/controllers/teams_controller.rb
  app/controllers/teams_users_controller.rb
  app/views/join_team_requests/index.html.erb
  app/views/shared_scripts/_selectTable.html.erb
  app/views/teams_users/list.html.erb
  config/routes.rb
  db/schema.rb
  spec/controllers/advertise_for_partner_controller_spec.rb
  spec/controllers/join_team_request_controller_spec.rb
  spec/controllers/student_teams_controller_spec.rb
  spec/controllers/teams_controller_spec.rb
  spec/controllers/teams_users_controller_spec.rb
  spec/factories/factories.rb
  spec/support/teams_shared.rb
Labels: Needs Review, Merge

#2210 Rubo cop lint
  .github/workflows/rubocop.yml
  .rubocop.yml
Labels: dev ops

#2211 Fix email
  app/controllers/users_controller.rb
  config/environments/development.rb
Labels: beta

#2212 content page controller test cases
  app/controllers/content_pages_controller.rb
  spec/controllers/content_pages_controller_spec.rb
  spec/factories/factories.rb
Labels: testing, beta

#2213 Model tests
  app/controllers/review_bids_controller.rb
  app/models/review_bid.rb
  db/schema.rb
  spec/models/review_bid_spec.rb
  spec/models/sign_up_topic_spec.rb
  spec/models/vm_question_response_spec.rb
Labels: testing, beta
