Repository expertiza/expertiza, pull requests merged in 2022-02, with the labels that each got.

#2221 Add flash for duplicate
  app/controllers/users_controller.rb
Labels: UI

#2224 Participant addition bug fix
  app/controllers/participants_controller.rb
  app/helpers/participants_helper.rb
  app/models/participant.rb
  db/schema.rb
  spec/models/participant_spec.rb
Labels: High Priority, UI, beta

#2225 add eager loading to solve n+1 problem
  Gemfile
  Gemfile.lock
  app/controllers/tree_display_controller.rb
  app/models/feedback_response_map.rb
  app/models/instructor.rb
  app/models/student_task.rb
  app/models/user.rb
  app/views/reports/_feedback_report.html.erb
  app/views/shared/_flash_notifications.html.erb
  config/environments/development.rb
  spec/models/feedback_response_map_spec.rb
  spec/models/instructor_spec.rb
Labels: beta

#2137 E2161. Merging Role based reviewing with Topic based reviewing
  app/assets/javascripts/duties.coffee
  app/assets/stylesheets/duties.scss
  app/assets/stylesheets/scaffolds.scss
  app/controllers/assignments_controller.rb
  app/controllers/duties_controller.rb
  app/controllers/participants_controller.rb
  app/controllers/response_controller.rb
  app/controllers/student_teams_controller.rb
  app/controllers/teams_users_controller.rb
  app/models/assignment.rb
  app/models/assignment_form.rb
  app/models/assignment_participant.rb
  app/models/duty.rb
  app/models/teammate_review_response_map.rb
  app/views/assignments/edit/_due_dates.html.erb
  app/views/assignments/edit/_general.html.erb
  app/views/assignments/edit/_review_strategy.html.erb
  app/views/assignments/edit/_rubrics.html.erb
  app/views/courses/new.html.erb
  app/views/duties/_actions.html.erb
  app/views/duties/_add_duties.html.erb
  app/views/duties/_add_duty.html.erb
  app/views/duties/_checkbox.html.erb
  app/views/duties/_duty.html.erb
  app/views/duties/_table_header.html.erb
  app/views/duties/_table_line.html.erb
  app/views/duties/edit.html.erb
  app/views/duties/new.html.erb
  app/views/student_review/_set_dynamic_review.html.erb
  app/views/student_teams/_select_duty_form.html.erb
  app/views/student_teams/view.html.erb
  config/routes.rb
  db/migrate/20211102232519_create_duties.rb
  db/migrate/20211102232536_add_id_to_assignment_questionnaires.rb
  db/migrate/20211102232559_add_column2_to_assignments.rb
  db/migrate/20211102232620_add_column_to_assignments.rb
  db/migrate/20211102232926_add_duty_id_to_participants.rb
  db/migrate/20211110161054_add_duty_id_to_teams_users.rb
  db/migrate/20211122083330_fix_column_name.rb
  db/migrate/20211123205149_fix_column_name2.rb
  db/migrate/20220111023859_rename_is_duty_based_assignment_to_duty_based_assignment.rb
  db/migrate/20220114003928_rename_duty_name_to_name.rb
  db/schema.rb
  spec/controllers/duties_controller_spec.rb
  spec/controllers/participants_controller_spec.rb
  spec/controllers/teams_users_controller_spec.rb
  spec/factories/factories.rb
  spec/lib/scoring_spec.rb
  spec/models/assignment_form_spec.rb
  spec/models/assignment_spec.rb
  spec/models/duty_spec.rb
  spec/models/teammate_review_response_map_spec.rb
  test/controllers/conference_controller_test.rb
  test/fixtures/sample_reviews.yml
  test/models/sample_review_test.rb
Labels: Needs Review, Many Changes, beta, needs manual testing

#2236 UI and flash msg fixes
  app/helpers/access_helper.rb
  app/views/auth/_login.html.erb
Labels: UI, beta

#2240 Improvements to Team Management as an Instructor - Inheritance and Bequeathal
  app/controllers/teams_controller.rb
  app/controllers/teams_users_controller.rb
  app/models/assignment.rb
  app/models/course.rb
  app/models/team.rb
  app/views/participants/_links.html.erb
  app/views/teams/_team.html.erb
  app/views/teams/list.html.erb
  app/views/teams/list_assignments.html.erb
  app/views/teams/new.html.erb
  app/views/tree_display/_page_footer.html.erb
  app/views/tree_display/actions/_teams_actions.html.erb
  config/routes.rb
  spec/controllers/teams_controller_spec.rb
  spec/controllers/teams_users_controller_spec.rb
  spec/models/assignment_spec.rb
  spec/models/course_spec.rb
  spec/support/teams_shared.rb
Labels: new feature, bug, Needs Review, UI, beta, needs manual testing

#2244 fix issue #2234
  app/controllers/users_controller.rb
Labels: bug, UI, beta

#2245 Issue fix on the user controller and list,
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/users/list.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  spec/controllers/users_controller_spec.rb
Labels: refactor, bug, performance, UI, beta

#2246 Export details fix
  app/controllers/export_file_controller.rb
  app/models/user.rb
  app/views/export_file/_users.html.erb
  spec/models/user_spec.rb
Labels: bug, beta

#2248 grade view bug fixes
  app/assets/javascripts/tree_display.jsx
  app/controllers/answer_controller.rb
  app/controllers/automated_metareviews_controller.rb
  app/controllers/due_date_controller.rb
  app/controllers/grades_controller.rb
  app/controllers/response_controller.rb
  app/controllers/survey_deployment_controller.rb
  app/controllers/waitlists_controller.rb
  app/helpers/authorization_helper.rb
  app/helpers/course_helper.rb
  app/helpers/questionnaire_helper.rb
  app/helpers/tree_display_helper.rb
  app/models/assignment_participant.rb
  app/models/instructor.rb
  app/models/role.rb
  app/models/rscore.rb
  app/models/ta.rb
  app/models/waitlist.rb
  app/views/assignment_survey_questionnaires/assign.html.erb
  app/views/assignment_survey_questionnaires/list.html.erb
  app/views/assignments/edit/_due_dates.html.erb
  app/views/assignments/edit/_other.html.erb
  app/views/assignments/list_submissions.html.erb
  app/views/automated_metareviews/list.html.erb
  app/views/grades/_participant.html.erb
  app/views/grades/_participants_statistics.html.erb
  app/views/grades/_statistics_tab.html.erb
  app/views/grades/_tabbed_participant.html.erb
  app/views/grades/_view_heatgrid.html.erb
  app/views/grades/view_team.html.erb
  app/views/menu_items/_suckerfish.html.erb
  app/views/response/response.html.erb
  app/views/response/view.html.erb
  app/views/survey_deployment/generate_statistics.html.erb
  app/views/survey_deployment/list.html.erb
  app/views/survey_deployment/new.html.erb
  app/views/survey_deployment/pending_surveys.html.erb
  app/views/survey_deployment/view_responses.html.erb
  config/role_admin.yml
  config/role_instructor.yml
  config/role_student.yml
  config/role_super_admin.yml
  config/role_ta.yml
  config/routes.rb
  lib/scoring.rb
  spec/controllers/reports_controller_spec.rb
  spec/controllers/survey_deployment_controller_spec.rb
  spec/models/instructor_spec.rb
  spec/models/ta_spec.rb
Labels: refactor, Needs Review, Many Changes, UI, beta, needs manual testing

#2249 Fix Rubocop Scope Problem
  .github/config/rubocop_linter_action.yml
  .github/workflows/rubocop.yml
  Dangerfile
  app/controllers/assessment360_controller.rb
  app/controllers/conference_controller.rb
  app/controllers/controller_actions_controller.rb
  app/controllers/impersonate_controller.rb
  app/controllers/publishing_controller.rb
  app/controllers/questionnaires_controller.rb
  app/controllers/quiz_questionnaires_controller.rb
  app/controllers/reputation_web_service_controller.rb
  app/controllers/response_controller.rb
  app/controllers/review_bids_controller.rb
  app/controllers/review_mapping_controller.rb
  app/controllers/sample_reviews_controller.rb
  app/controllers/sign_up_sheet_controller.rb
  app/controllers/site_controllers_controller.rb
  app/controllers/student_task_controller.rb
  app/controllers/suggestion_controller.rb
  app/controllers/teams_controller.rb
  app/controllers/teams_users_controller.rb
  app/controllers/users_controller.rb
  app/helpers/access_helper.rb
  app/helpers/assignment_helper.rb
  app/helpers/charts_helper.rb
  app/helpers/join_team_requests_helper.rb
  app/helpers/penalty_helper.rb
  app/helpers/questionnaire_helper.rb
  app/helpers/report_formatter_helper.rb
  app/helpers/review_mapping_helper.rb
  app/helpers/security_helper.rb
  app/helpers/student_task_helper.rb
  app/helpers/submitted_content_helper.rb
  app/helpers/summary_helper.rb
  app/mailers/mail_worker.rb
  app/mailers/mailer.rb
  app/models/analytic/questionnaire_analytic.rb
  app/models/assignment.rb
  app/models/assignment_form.rb
  app/models/assignment_participant.rb
  app/models/content_page.rb
  app/models/controller_action.rb
  app/models/instructor.rb
  app/models/metareview_response_map.rb
  app/models/quiz_response_map.rb
  app/models/response.rb
  app/models/response_map.rb
  app/models/review_response_map.rb
  app/models/sign_up_sheet.rb
  app/models/sign_up_topic.rb
  app/models/team.rb
  app/models/teammate_review_response_map.rb
  app/models/teams_user.rb
  app/models/text_area.rb
  app/models/true_false.rb
  app/models/user.rb
  app/models/waitlist.rb
Labels: dev ops

#2254 Additional Rspec Examples
  app/models/view_translation_substitutor.rb
  spec/lib/hamer_spec.rb
  spec/models/view_translation_substitutor_spec.rb
Labels: testing, beta

#2259 fix issue #2257
  app/controllers/conference_controller.rb
  app/controllers/users_controller.rb
  app/helpers/conference_helper.rb
  app/models/user.rb
  app/views/users/_password.html.erb
  app/views/users/_user.html.erb
  spec/controllers/conference_controller_spec.rb
  spec/controllers/invitations_controller_spec.rb
  spec/controllers/password_retrieval_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/models/administrator_spec.rb
  spec/models/lock_spec.rb
  spec/models/user_spec.rb
Labels: UI, beta

#2261 Check email pref by default
  app/views/users/_prefs.html.erb
Labels: UI, beta

#2260 Auth controller spec
  app/controllers/auth_controller.rb
  config/routes.rb
  spec/controllers/auth_controller_spec.rb
Labels: testing, Needs Review, beta

#2265 Role controller spec
  app/controllers/roles_controller.rb
  spec/controllers/roles_controller_spec.rb
Labels: testing, beta

#2273 Fix the Rubric Delivering Order Problem
  app/views/response/response.html.erb
Labels: bug, UI, beta

#2277 Account request email fix
  app/controllers/account_request_controller.rb
  app/controllers/users_controller.rb
  app/views/account_request/new.html.erb
Labels: new feature, email, beta

#2280 Mail on invite
  app/controllers/invitations_controller.rb
  app/views/mailer/partials/_invite_participant_to_team_html.html.erb
  app/views/mailer/partials/_invite_participant_to_team_plain.html.erb
  app/views/student_teams/view.html.erb
Labels: email, beta

#2274 Improve e-mail notifications
  app/controllers/submitted_content_controller.rb
  app/helpers/mailer_helper.rb
  app/mailers/mail_worker.rb
  app/mailers/mailer.rb
  app/models/participant.rb
  app/views/import_file/start.html.erb
  app/views/mailer/partials/_updated_submission_since_review_html.html.erb
  app/views/mailer/partials/_updated_submission_since_review_plain.html.erb
  spec/features/assignment_submission_spec.rb
  spec/models/participant_spec.rb
  spec/workers/sidekiq_mail_worker_spec.rb
Labels: email, beta
